### ISSUE TITLE
Guest User Features Checklist

### ISSUE THREAD

**Issue by russellkerns** [grace-shopper-project/grace-shopper-project#110]
- [x] Products
    - [x] View all products
    - [x] Filter by category 
    - [x] Search 
    - [x] View single product incl. description, photos & reviews

  - [x] Cart
    - [x] Add to cart
    - [x] Remove from cart
    - [x] Edit quantities of product
    - [x] Cart persistence with refresh
    - [x] Cart persistence with login/logout

  - [x] Checkout
    - [x] Purchase cart
    - [x] Specify shipping address
    - [x] Specify email 
    - [ ] Receive order confirmation email 
    - [ ] Receive order shipped email 
    - [ ] Receive order delivered email 

  - [x] Account Management
    - [x] Create own account 
    - [x] Login with Google/Facebook
